### PR TITLE
fix: 🐛 Zip up produced artifacts

### PR DESCRIPTION
**Pull request by berkus**
- Put everything into a zip file
- Keep gerbers and drills in their own zip file within the outer zip package

- Produce the same structure zip file in all pipelines, so you can review what goes into it starting from the PR builds.

### CODE REVIEW

**Comment by Yatekii** [comment]
Why two zips? :) I would prefer just one layer :)

**Comment by berkus** [comment]
@Yatekii ah, sorry, we discussed with Emil that this will be better for JLCPCB, I don't have a preference personally but if it actually makes it easier to submit the files for production that's what I'd choose.

**Comment by berkus** [comment]
@korken89 pls download the Artifact from the bottom of this page https://github.com/probe-rs/rusty-probe/actions/runs/12200986874 and check that it's in a good format.

**Comment by korken89** [comment]
Looks good!

**Review by korken89 — APPROVED** [review]

**Comment by korken89** [comment]
@berkus The `generate_outputs` never run so I can't merge. Do we need to enable something more?

**Comment by korken89** [comment]
Huh, that one does not exist in the repo... I'll check if it's a setting

**Comment by berkus** [comment]
> I'll check if it's a setting

I think it was the old step name, but GH doesn't remove it from required checks even if it's gone from the pipelines, security measure.

**Pull request merged**
