### PR TITLE
Update README.md on Target support description

### PR DESCRIPTION
**Pull request by acedogblast**
Changed probe comparison chart to be more accurate. This addresses #15.

### CODE REVIEW

**Review by Yatekii — COMMENTED** [review]
Thanks for this :)

The Rusty Probe supports SWO and UART as well. Additionally, we can just write SWD instead of "Serial Wire Debug", same for SWO.
Also, ST-Link has SWO too.

**Comment by acedogblast** [comment]
Changed to shorten the text per your suggestion. So Rusty Probe firmware already has SWO and UART support? That means the firmware TODO list needs updating as well.

**Review by Yatekii — DISMISSED** [review]

**Comment by Yatekii** [comment]
Oh, I am not sure it is implemented. Could you chime in here, @korken89?

**Comment by korken89** [comment]
Currently the probe has the firmware for SWD and the UART is activated, but we use the UART for debug outputs right now. :)

**Review by berkus — APPROVED** [review]

**Comment by berkus** [comment]
@Yatekii @korken89 lets merge this one too?

**Review by korken89 — APPROVED** [review]
Thank you!

**Pull request merged**
